spring.application.name=pethub

# RSA Keys
rsa.private-key=classpath:certs/private_key.pem
rsa.public-key=classpath:certs/public_key.pem

# Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/pethub
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate

